## 생활인구 데이터셋 전처리

In [1]:
import pandas as pd
import numpy as np

### 0. 데이터 불러오기(테스트)

In [5]:
df = pd.read_csv('../data/rawdata/LOCAL_PEOPLE_DONG_202101.csv')
df.reset_index(inplace = True)
cols = df.columns.tolist()
cols.pop(0)
df = df.drop(df.columns[-1], axis=1)
df.columns = cols

### 1. 데이터 병합(21년)

In [3]:
import pandas as pd

# 12개의 CSV 파일의 파일 이름을 리스트에 저장
csv_files = ['rawdata/LOCAL_PEOPLE_DONG_202101.csv', 'rawdata/LOCAL_PEOPLE_DONG_202102.csv',
             'rawdata/LOCAL_PEOPLE_DONG_202103.csv', 'rawdata/LOCAL_PEOPLE_DONG_202104.csv',
             'rawdata/LOCAL_PEOPLE_DONG_202105.csv', 'rawdata/LOCAL_PEOPLE_DONG_202106.csv',
             'rawdata/LOCAL_PEOPLE_DONG_202107.csv', 'rawdata/LOCAL_PEOPLE_DONG_202108.csv',
             'rawdata/LOCAL_PEOPLE_DONG_202109.csv', 'rawdata/LOCAL_PEOPLE_DONG_202110.csv',
             'rawdata/LOCAL_PEOPLE_DONG_202111.csv', 'rawdata/LOCAL_PEOPLE_DONG_202112.csv']

# 결과를 저장할 빈 데이터프레임 생성
combined_df = pd.DataFrame()

# 각 파일에 대해 작업 수행
for file in csv_files:
    # CSV 파일 읽기
    PATH = '../data/'
    df = pd.read_csv(PATH + file)

    # 인덱스 재설정
    df.reset_index(inplace=True)

    # 컬럼 이름 수정
    cols = df.columns.tolist()
    cols.pop(0)  # 첫 번째 컬럼 제거
    df = df.drop(df.columns[-1], axis=1)  # 마지막 컬럼 제거
    df.columns = cols

    # 데이터를 기존 데이터프레임에 추가
    combined_df = pd.concat([combined_df, df])

# 결과 데이터프레임 출력
combined_df

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20210101,0,11110515,14473.8890,504.7535,321.6298,474.2765,624.4867,507.3616,405.9607,...,424.0524,459.3872,534.8354,673.7167,746.3401,609.6886,590.1671,422.7630,339.8220,1138.9208
1,20210101,0,11110530,13299.5313,364.9421,162.1967,254.0620,318.9359,449.9919,419.8851,...,459.9216,537.1230,667.1788,565.2750,603.2522,522.3540,543.4003,447.2674,363.1686,1138.6352
2,20210101,0,11110550,15518.3772,418.3329,324.3693,380.5245,529.5754,470.6277,415.8823,...,417.9814,448.0938,621.1825,636.9613,840.1881,692.5841,693.3884,630.9412,421.9502,1456.3029
3,20210101,0,11110600,5108.9481,122.7939,86.6778,90.4754,203.9829,137.2541,124.3374,...,127.1385,180.1318,183.2139,268.8835,268.7073,247.4089,227.3631,163.6567,135.4872,406.3143
4,20210101,0,11110700,7907.7246,224.1087,106.2126,153.8756,194.7256,272.8423,315.6010,...,280.9285,279.1961,309.0617,316.6311,371.2800,370.3215,377.7498,258.4794,213.1911,532.8069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315451,20211231,23,11470540,21687.6749,861.7272,727.1708,1005.5965,681.5753,729.5826,598.0799,...,767.5661,655.7412,700.6698,843.2792,1226.9588,981.3435,924.6850,617.5297,475.8060,1213.4361
315452,20211231,23,11740685,56597.5455,1839.0829,889.3184,1335.2357,1477.6366,1976.8694,2141.6605,...,2107.8068,2085.6888,2268.4922,1980.8497,2519.0302,2252.5037,2613.0954,2397.8625,1769.1395,3969.7268
315453,20211231,23,11500611,33165.7067,1978.0254,1060.2853,1113.7417,915.0305,928.4453,826.6652,...,1004.7462,865.8292,1372.5672,1538.8561,1596.6038,1211.5687,1151.6991,992.2469,745.9197,2002.0061
315454,20211231,23,11215810,36194.0265,1573.0999,1329.8560,1601.7697,961.0242,864.6878,805.5853,...,1035.1837,916.1508,1601.0251,1854.1259,2049.0453,1483.5373,1326.8725,905.1418,630.0094,1436.7711
315455,20211231,23,11560550,22589.9182,807.3828,280.0176,358.6660,626.8327,986.6300,1275.7233,...,1118.6744,1226.6123,1117.9995,861.5416,847.6130,785.8174,947.0463,741.3184,587.2430,1197.3963

In [5]:
PATH = '/content/drive/MyDrive/Colab Notebooks/공모전/data/'
combined_df.to_csv(PATH + 'LOCAL_PEOPLE_DONG_2021(merged).csv',index = False, encoding = 'utf-8-sig')